#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")"/..

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -o dist/darwin-amd64/pusher-interview-test ./pusher-interview-test
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o dist/linux-amd64/pusher-interview-test ./pusher-interview-test
